# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Mehmet Raşit Narçiçek

"""
project_metadata.py — Single source of truth for project provenance metadata.

Every exported artifact (SVG, XLSX, JSON manifest, HTML/PDF report) embeds the same
project name, version, author, ORCID, license and repository strings.
"""

from __future__ import annotations
from typing import Any, Dict, List, Tuple

PROJECT_NAME = "RASH-HIT Fractal Studio"
PROJECT_VERSION = "1.0.0"
PROJECT_AUTHOR = "Mehmet Raşit Narçiçek"
PROJECT_ORCID = "https://orcid.org/0009-0005-3423-255X"
PROJECT_LICENSE = "Apache-2.0"
PROJECT_REPOSITORY = "https://github.com/rasitnarcicek/RASH-HIT-Fractal-Studio"
PROJECT_CITATION_FILE = "CITATION.cff"

PROJECT_TITLE = f"{PROJECT_NAME} v{PROJECT_VERSION}"


def provenance_pairs() -> List[Tuple[str, str]]:
    """Label/value provenance rows used by workbook cover sheets."""
    return [
        ("Generated By", PROJECT_TITLE),
        ("Author", PROJECT_AUTHOR),
        ("ORCID", PROJECT_ORCID),
        ("License", PROJECT_LICENSE),
        ("Repository", PROJECT_REPOSITORY),
        ("Citation Metadata", f"See {PROJECT_CITATION_FILE}"),
    ]


def svg_provenance_block() -> List[str]:
    """SVG comment + <metadata> provenance lines emitted into generated figures."""
    return [
        f'  <!-- Generated by {PROJECT_TITLE} | Author: {PROJECT_AUTHOR} '
        f'| ORCID: {PROJECT_ORCID} | License: {PROJECT_LICENSE} '
        f'| Repository: {PROJECT_REPOSITORY} -->',
        '  <metadata>',
        '    <provenance>',
        f'      <generator>{PROJECT_TITLE}</generator>',
        f'      <author>{PROJECT_AUTHOR}</author>',
        f'      <orcid>{PROJECT_ORCID}</orcid>',
        f'      <license>{PROJECT_LICENSE}</license>',
        f'      <repository>{PROJECT_REPOSITORY}</repository>',
        '    </provenance>',
        '  </metadata>',
    ]


def manifest_project_block() -> Dict[str, Any]:
    """Project descriptor embedded in manifest/manifest.json."""
    return {
        "name": PROJECT_NAME,
        "version": PROJECT_VERSION,
        "license": PROJECT_LICENSE,
        "repository": PROJECT_REPOSITORY,
        "author": PROJECT_AUTHOR,
        "orcid": PROJECT_ORCID,
        "citation_file": PROJECT_CITATION_FILE,
    }
