# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Mehmet Raşit Narçiçek

"""
xlsx_styles.py — Shared openpyxl style palette and worksheet helpers.

The workbook and the per-level technical tables use one identical visual language
(dark slate headers, zebra body rows, thin grey cell borders). This module owns the
style objects plus the repeated header/axis/save routines built on top of them.
"""

from __future__ import annotations
import time
from pathlib import Path
from typing import Optional

from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from backend.project_metadata import PROJECT_AUTHOR, PROJECT_TITLE

MONO = "Consolas"


def _solid(color: str) -> PatternFill:
    return PatternFill(start_color=color, end_color=color, fill_type="solid")


def _uniform_border(color: str) -> Border:
    side = Side(style="thin", color=color)
    return Border(left=side, right=side, top=side, bottom=side)


DARK_HEADER_FILL = _solid("1E293B")
ZEBRA_FILL = _solid("F8FAFC")
WHITE_FILL = _solid("FFFFFF")
MAP_FILLED_FILL = _solid("60A5FA")
MAP_EMPTY_FILL = _solid("FFFFFF")
COORD_FILLED_FILL = _solid("BFDBFE")
COORD_EMPTY_FILL = _solid("F8FAFC")

THIN_BORDER = _uniform_border("D1D5DB")
WHITE_BORDER = _uniform_border("FFFFFF")

DARK_HEADER_FONT = Font(name=MONO, size=10, bold=True, color="FFFFFF")
SUB_FONT = Font(name=MONO, size=9, italic=True, color="4B5563")
LABEL_FONT = Font(name=MONO, size=9, bold=True, color="0F172A")
VALUE_FONT = Font(name=MONO, size=9, color="0F172A")
SECTION_TITLE_FONT = Font(name=MONO, size=14, bold=True, color="1E293B")
SHEET_TITLE_FONT = Font(name=MONO, size=12, bold=True, color="1E293B")

ALIGN_CENTER = Alignment(horizontal="center", vertical="center")
ALIGN_RIGHT = Alignment(horizontal="right", vertical="center")
ALIGN_LEFT = Alignment(horizontal="left", vertical="center")


def coord_font(size: int, is_filled: bool) -> Font:
    """Monospaced font for coordinate map cells, styled by occupancy."""
    return Font(name=MONO, size=size, bold=is_filled, color="1E3A8A" if is_filled else "475569")


def set_workbook_properties(wb, title: str, subject: str, keywords: str, description: str) -> None:
    wb.properties.creator = PROJECT_AUTHOR
    wb.properties.title = title
    wb.properties.subject = subject
    wb.properties.keywords = keywords
    wb.properties.description = description


def style_header_row(ws, row: int, num_cols: int, alignment: Optional[Alignment] = None) -> None:
    """Applies the dark slate header styling to ``num_cols`` cells of ``row``."""
    for col_idx in range(1, num_cols + 1):
        cell = ws.cell(row=row, column=col_idx)
        cell.fill = DARK_HEADER_FILL
        cell.font = DARK_HEADER_FONT
        if alignment is not None:
            cell.alignment = alignment


def _style_axis_header(cell) -> None:
    cell.alignment = ALIGN_CENTER
    cell.font = DARK_HEADER_FONT
    cell.fill = DARK_HEADER_FILL
    cell.border = WHITE_BORDER


def write_grid_axis_headers(ws, cols: int, column_width: float, header_row: int = 6) -> None:
    """Writes the ``Grid`` corner label and the ``C01..Cnn`` column axis headers."""
    ws.column_dimensions["A"].width = 4
    ws.column_dimensions["B"].width = 10
    ws.row_dimensions[header_row - 1].height = 24
    ws.row_dimensions[header_row].height = 24

    _style_axis_header(ws.cell(row=header_row, column=2, value="Grid"))

    for c in range(cols):
        _style_axis_header(ws.cell(row=header_row, column=c + 3, value=f"C{c + 1:02d}"))
        ws.column_dimensions[get_column_letter(c + 3)].width = column_width


def write_grid_row_header(ws, excel_row: int, row_idx: int) -> None:
    """Writes the ``Rnn`` row axis header for a grid map row."""
    ws.row_dimensions[excel_row].height = 20
    _style_axis_header(ws.cell(row=excel_row, column=2, value=f"R{row_idx + 1:02d}"))


def save_workbook_with_retry(wb, path: Path, attempts: int = 5, delay: float = 0.5) -> bool:
    """Saves a workbook, retrying while the target file is locked by another process."""
    for _ in range(attempts):
        try:
            wb.save(path)
            return True
        except PermissionError:
            time.sleep(delay)
    return False


ACADEMIC_WORKBOOK_DESCRIPTION = f"Generated by {PROJECT_TITLE}"
